base:
  mass: 0.8               # Base mass in Kg
  x_size: 0.16            # Dimension in x axis
  y_size: 0.16            # Dimension in y axis
  z_size: 0.15            # Dimension in z axis
  mesh: 'chassis.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  scale: '0.001 0.001 0.001'
