mass: 0.02        # Wheel mass in Kg
radius: 0.04      # Wheel radius in m
length: 0.01      # Wheel length in m, considering is as a cylinder
mesh: 'pololu-wheel-80x10mm-black.stl'  # Leave it empty ('') to have a red wheel
scale: '0.001 0.001 0.001'
x_offset: 0.0
y_offset: -0.031
z_offset: -0.017
